### PR TITLE
Bugfixes: Allow base props "className" and "style" to work on all components, fix some event listener issues.

### PR DESCRIPTION
**Pull request by weltraumpirat**
Hi, this is a workaround to fix an issue that prevents className and style base properties from being forwarded to web components. See github.com/facebook/react/issues/4933

I noticed that there was no way I could style individual components, so I figured out a way to make it work. 

I have tried to preserve the styling as well as I could, but suppressed a few warnings about empty tags in tests.

### CODE REVIEW

**Comment by gojutin** [comment]
Thanks for all the pull requests! It looks like the tests are all passing. Did you test out each of your changes in Storybook to make sure everything works as expected?

**Comment by weltraumpirat** [comment]
Hi Justin,

I did that just now: It seems to work fine. 

I used the components in a showcase app I’m building. I found all the bugs that way, and fixed because I had to. They do work in that setting now -- except for an issue with the listbox that is also present in the web components themselves, that is ;)

Lmk if I can help out with other stuff. I like both the wired-elements and your implementation, and I'm probably going to be using it more, anyway.

**Comment by gojutin** [comment]
Great, thanks again. I will comb through it a bit more, but everything looks good so far.  

As far as helping, bug fixes are always great. I'm sure there a some bugs that I didn't find. So, if you find one, please feel free to file an issue and/or submit a PR with the fix.  Also, feel free to put a link to your showcase in the README 😄

**Comment by weltraumpirat** [comment]
Will do, once it is public :) Thanks for maintaining this - super useful!

**Comment by gojutin** [comment]
Good morning, I pulled in your changes and published a new `0.1.5` release with these changes. Thanks again for your contributions! 

https://github.com/gojutin/react-wired-elements/releases/tag/v0.1.5

**Pull request merged**
